### ISSUE TITLE
"ok" button stays non-responsive for configuration windows

### ISSUE THREAD

**Issue by sturmkev** [spatial-data-lab/knime-geospatial-extension#26] opened 2022-11-04 15:53 UTC
After my recent pull (and nightly build update), the "ok" button of a configuration window (of any geospatial node) seems to be non-responsive. If I click the button nothing happens and the configuration window remains open.

**Comment by sturmkev** [comment] 2022-11-04 15:54
it worked until yesterday (prior recent pull of master branch) though

**Comment by koettert** [comment] 2022-11-04 18:05
Same here. I contacted our colleagues to figure out what the problem is.

**Comment by koettert** [comment] 2022-11-04 18:20
This is a known problem which was fixed today and thus should be fixed in tomorrows nightly build. I will close this ticket here once I confirmed it is fixed.

**Comment by koettert** [comment] 2022-11-07 08:41
Problem is fixed with the latest nightly build update of the KNIME Analytics Platform

**Closed by koettert** 2022-11-07 08:41 UTC
